language: ruby

rvm:
  - 2.2.5

before_install:
  - gem install bundler
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml

before_script:
  - bundle exec rake db:migrate

